export const Images =[
    {
        id:0,
        url:'https://valpack.by/wp-content/uploads/2020/05/0557.jpg'
    },
    {
        id:1,
        url:'https://studlive.by/wp-content/uploads/2020/06/img_0645.jpg'
    },
    {
        id:2,
        url:'https://static.tildacdn.com/tild3233-3931-4334-b566-666336346562/1_DSC_1957_1_.jpg'
    }
]


export const Images2 =[
    {
        id:0,
        url:''
    },
    {
        id:1,
        url:''
    },
    {
        id:2,
        url:''
    },
    {
        id:3,
        url:''
    },
    {
        id:4,
        url:''
    },
    {
        id:5,
        url:''
    },
    {
        id:6,
        url:''
    },
    {
        id:7,
        url:''
    }
]